name: test
on:
- pull_request
jobs:
  focal:
    container:
      image: swift:6.2-bookworm
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: swift test
  thread:
    container:
      image: swift:6.2-bookworm
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: swift test --sanitize=thread
  address:
    container:
      image: swift:6.2-bookworm
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: ASAN_OPTIONS=detect_leaks=0 swift test --sanitize=address
  focal-5-10:
    container:
      image: swift:5.10-focal
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: swift test
  thread-5-10:
    container:
      image: swift:5.10-focal
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: swift test --sanitize=thread
  address-5-10:
    container:
      image: swift:5.10-focal
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: ASAN_OPTIONS=detect_leaks=0 swift test --sanitize=address
